### ISSUE TITLE
Issue:  matrix generation

### ISSUE THREAD

**Issue by ig624** [michaelllo1993/BALCONY#10]
Dear BALCONY developers,
Thank you very much for the development of this useful package. Hoverer, I am having some problems with the initial step of `alignment2matrix`. I think the problem is more related on the task done by  `seqinr::read.alignment`. Indeed, by using all the four formats available in `read.alignment `, once I run `alignment2matrix`, only NAs are generated and by rinning `warnings()`, the following messages appear:
`In seqinr::s2c(alignment$seq[i]) : Wrong argument type in s2c(), NA returned
`
The problem persists even if I use the alignments available in the data folder of the `seqinr `package.
Maybe I am wrong, but I believe the problem seems to be connected to a `list vs string scenario`. the` as.string=T` argument in `read.alignment` does not work when the input is fasta; 
Have you ever seen this error? I am sure it is a silly mistake, but I do not really understand the reasons behind it.

**Comment by stolarczyk** [comment]
thanks for reporting @ig624. You're right, the issue is caused by `seqinr::read.alignment()$seq` being a list rather than string, which is expected. 

There must have been an output format change in `seqinr::read.alignment` function. Even their docs say that `seq` is a vector of strings:

```
Value:

     An object of class ‘alignment’ which is a list with the following
     components:

     seq: a vector of strings containing the aligned sequences
```
I'll make a fix on a `dev` branch (so go ahead and use that one for now) and will wait with the release since the docs/code discrepancy is confusing.
